### ISSUE TITLE
CompiledIncludeNode fails to properly import files

### ISSUE THREAD

**Issue by wyrickre** [mvel/mvel#276] opened 2021-09-30 00:34 UTC
It appears that the file is read as one line because BufferedReader.readline() eats the newline character here:
https://github.com/mvel/mvel/blob/5ab6d1c670e8494dac01bef6bf22c71f030784c2/src/main/java/org/mvel2/templates/res/CompiledIncludeNode.java#L101

If the first thing in the template being imported is an @comment{\n .... \n}\n - all those newlines get eaten and the entire file is ignored.

I fixed my local copy by just re-adding a newline character, but this needs a "proper" cleanup in that this code should be de-duped with the code in IncludeNode.java that does basically the same thing (read a file to a String) without this bug.

**Comment by MalcolmOdd** [comment] 2022-01-22 16:27
Duplicate of https://github.com/mvel/mvel/issues/152 (which is still open). It is a bug since it is inconsistent with how the main file is processed.

**Closed** 2023-06-06 08:39 UTC
